version: '1'
services:
    nginx-server:
        image: nginx:latest
        # Imagem padrão do Nginx no Docker Hub
        build:
            context: ./
            dockerfile: ./nginx-server/Dockerfile
        # command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
        ports:
            - "80:80"
        restart: always
    app:
        build:
            context: ./
            dockerfile: ./app/Dockerfile
        depends_on:
            - nginx-server
